#!/bin/bash 
######################################
#            Shell script            #
# Author: H.L.                       #
# TPL Version: 0.1                   #
######################################

#========================Global variables
APPVER="0.1b"
MYDIR=`echo $0`
FILENAME=`echo $MYDIR|rev|cut -d / -f 1|rev`
MYDIR=${MYDIR%%/$FILENAME}
#=======================Include base library

. /etc/system.conf
. $srvDIR/_dev_system/functions

CLIENTIP=$(get_ssh_ip)
ROUTETABLE=proxyGB
ROUTEDEV=tapSangouGB
ROUTEGW=2.4.2.1

echo -e "${COLOR_LIME}GB Route script.... ${COLOR_END}"
echo -e "${COLOR_RED}Client ip: ${CLIENTIP} ${COLOR_END}"


start(){
 run "ip rule add from $CLIENTIP table $ROUTETABLE" "Add source ip"
 run "ip route add default table $ROUTETABLE via $ROUTEGW dev $ROUTEDEV" "Add source rule"
}

stop(){
 run "ip route del default table $ROUTETABLE via $ROUTEGW dev $ROUTEDEV" "Del source rule"
 run "ip rule del from $CLIENTIP table $ROUTETABLE" "Del source ip"
}

list(){
 echo 
 echo "List(active):"
 echo "--------------------------------"
 
 LIST=`ip rule list|grep $ROUTETABLE`
 for item in $LIST
 do
   echo $item | cut -d " " -f 2
 done
 #ip route list table $ROUTETABLE
 echo
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  list)
       list
       ;;
  *)
	echo $"Usage: $prog {start|stop|list}"
	RETVAL=3
esac


