#!/bin/bash 
######################################
#            Shell script            #
# Author: H.L.                       #
# TPL Version: 0.1                   #
######################################

#========================Global variables
APPVER="0.1b"
MYDIR=`echo $0`
MYREALDIR=`readlink $MYDIR`
if [ ! -z $MYREALDIR ]; then  MYDIR=$MYREALDIR;  fi;
FILENAME=`echo $MYDIR|rev|cut -d / -f 1|rev`
MYDIR=${MYDIR%%/$FILENAME}
#=======================Include base library

. /etc/system.conf
. $srvDIR/_dev_system/functions

CLIENTIP=$(get_ssh_ip)

echo -e "${COLOR_LIME}$FILENAME, $APPVER.... ${COLOR_END}"
#echo -e "${COLOR_RED}Client ip: ${CLIENTIP} ${COLOR_END}"



#=====================main functions
#help about using of script
help(){
  echo $"Usage: $FILENAME {start|stop|list|help} {profile}"
}

#base actions
#$1 action
#$2 name
do_actions(){
 PROXY=$2
 if [ ! -e $MYDIR/conf/$PROXY ]; then
  write_error "[!] Proxy profile $2 not found."
  return 1
 else
  write_info "Using profile $2..."
 fi

  include "conf/$PROXY"

  case "$1" in
    start)     
     if [ "$PROXY" == "" ]; then
       write_error "[!] No profile passed"
       return 1
     fi
     route_client $ROUTETABLE $ROUTEDEV $ROUTEGW
    ;;  
    stop)
     if [ "$PROXY" == "" ]; then 
       write_error "[!] No profile passed"
       return 1
     fi
     unroute_client $ROUTETABLE $ROUTEDEV $ROUTEGW
     ;;
    list)
      if [ "$PROXY" == "" ]; then
        list_all
      else
        list $ROUTETABLE $ROUTEDEV $ROUTEGW
      fi
     ;;
    *)
    help
  esac
}

#====================================

# 1:  routetable
# 2:  routedev
# 3:  routegw
route_client(){
 ROUTETABLE=$1
 ROUTEDEV=$2
 ROUTEGW=$3
 run "ip rule add from $CLIENTIP table $ROUTETABLE" "Add source ip"
 run "ip route add default table $ROUTETABLE via $ROUTEGW dev $ROUTEDEV" "Add source rule"
}

# 1:  routetable
# 2:  routedev
# 3:  routegw
unroute_client(){
 ROUTETABLE=$1
 ROUTEDEV=$2
 ROUTEGW=$3
 run "ip route del default table $ROUTETABLE via $ROUTEGW dev $ROUTEDEV" "Del source rule"
 run "ip rule del from $CLIENTIP table $ROUTETABLE" "Del source ip"
}

# 1:  routetable
# 2:  routedev
# 3:  routegw
list(){
 ROUTETABLE=$1
 ROUTEDEV=$2
 ROUTEGW=$3
 echo "List(active):"
  
 LIST=`ip rule list|grep $ROUTETABLE`
 
 switch_delimiter '#'
 CN=0
 for item in $LIST
 do
	write_item "$CN" `echo $item | cut -d " " -f 2`
   CN=$((CN+1))
 done
 switch_delimiter
 
 #ip route list table $ROUTETABLE
 echo
}

#list available profiles
list_all(){
 echo  
 list=`ls $MYDIR/conf`
 for item in $list
 do
  write_header $item
  include conf/$item
  list $ROUTETABLE $ROUTEDEV $ROUTEGW
 done
}



#===================================check params

case "$1" in
  help)
  help
  ;;  
  *)
  do_actions "$1" "$2"
esac


