#!/bin/bash
######################################
#            Shell script            #
# Author: H.L.                       #
# TPL Version: 0.1                   #
######################################

#========================Global variables
APPVER="0.1b"
MYDIR=`echo $0`
MYREALDIR=`readlink $MYDIR`
if [ ! -z $MYREALDIR ]; then  MYDIR=$MYREALDIR;  fi;
FILENAME=`echo $MYDIR|rev|cut -d / -f 1|rev`
MYDIR=${MYDIR%%/$FILENAME}
#=======================Include base library
. $MYDIR/functions


# $1 - filename
if [ ! -z $1 ]; then
  run "cp -f $MYDIR/template $PWD/$1" "Create script from template"
  run "chmod u+x $PWD/$1" "Apply execute permissions"
fi